package hibernate;
// Generated 2017-4-26 14:48:25 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Administrator generated by hbm2java
 */
public class Administrator implements java.io.Serializable {

	private int administratorId;
	private Worker worker;
	private Set strategies = new HashSet(0);

	public Administrator() {
	}

	public Administrator(Worker worker) {
		this.worker = worker;
	}

	public Administrator(Worker worker, Set strategies) {
		this.worker = worker;
		this.strategies = strategies;
	}

	public int getAdministratorId() {
		return this.administratorId;
	}

	public void setAdministratorId(int administratorId) {
		this.administratorId = administratorId;
	}

	public Worker getWorker() {
		return this.worker;
	}

	public void setWorker(Worker worker) {
		this.worker = worker;
	}

	public Set getStrategies() {
		return this.strategies;
	}

	public void setStrategies(Set strategies) {
		this.strategies = strategies;
	}

}
