package hibernate;
// Generated 2017-4-26 14:48:25 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * Bookdecomp generated by hbm2java
 */
public class Bookdecomp implements java.io.Serializable {

	private String bookDecompId;
	private Rentform rentform;
	private Date bookDecompDate;
	private Integer bookDecompFine;
	private Date bookDecompStartTime;
	private Date bookDecompEndTime;
	private Integer bookDecompPayStatus;
	private Integer bookDecompFineType;
	private Date bookDecompLeaveTime;
	private Date bookDecompArriveTime;
	private String bookDecompCarNumber;

	public Bookdecomp() {
	}

	public Bookdecomp(String bookDecompId, Rentform rentform) {
		this.bookDecompId = bookDecompId;
		this.rentform = rentform;
	}

	public Bookdecomp(String bookDecompId, Rentform rentform, Date bookDecompDate, Integer bookDecompFine,
			Date bookDecompStartTime, Date bookDecompEndTime, Integer bookDecompPayStatus, Integer bookDecompFineType,
			Date bookDecompLeaveTime, Date bookDecompArriveTime, String bookDecompCarNumber) {
		this.bookDecompId = bookDecompId;
		this.rentform = rentform;
		this.bookDecompDate = bookDecompDate;
		this.bookDecompFine = bookDecompFine;
		this.bookDecompStartTime = bookDecompStartTime;
		this.bookDecompEndTime = bookDecompEndTime;
		this.bookDecompPayStatus = bookDecompPayStatus;
		this.bookDecompFineType = bookDecompFineType;
		this.bookDecompLeaveTime = bookDecompLeaveTime;
		this.bookDecompArriveTime = bookDecompArriveTime;
		this.bookDecompCarNumber = bookDecompCarNumber;
	}

	public String getBookDecompId() {
		return this.bookDecompId;
	}

	public void setBookDecompId(String bookDecompId) {
		this.bookDecompId = bookDecompId;
	}

	public Rentform getRentform() {
		return this.rentform;
	}

	public void setRentform(Rentform rentform) {
		this.rentform = rentform;
	}

	public Date getBookDecompDate() {
		return this.bookDecompDate;
	}

	public void setBookDecompDate(Date bookDecompDate) {
		this.bookDecompDate = bookDecompDate;
	}

	public Integer getBookDecompFine() {
		return this.bookDecompFine;
	}

	public void setBookDecompFine(Integer bookDecompFine) {
		this.bookDecompFine = bookDecompFine;
	}

	public Date getBookDecompStartTime() {
		return this.bookDecompStartTime;
	}

	public void setBookDecompStartTime(Date bookDecompStartTime) {
		this.bookDecompStartTime = bookDecompStartTime;
	}

	public Date getBookDecompEndTime() {
		return this.bookDecompEndTime;
	}

	public void setBookDecompEndTime(Date bookDecompEndTime) {
		this.bookDecompEndTime = bookDecompEndTime;
	}

	public Integer getBookDecompPayStatus() {
		return this.bookDecompPayStatus;
	}

	public void setBookDecompPayStatus(Integer bookDecompPayStatus) {
		this.bookDecompPayStatus = bookDecompPayStatus;
	}

	public Integer getBookDecompFineType() {
		return this.bookDecompFineType;
	}

	public void setBookDecompFineType(Integer bookDecompFineType) {
		this.bookDecompFineType = bookDecompFineType;
	}

	public Date getBookDecompLeaveTime() {
		return this.bookDecompLeaveTime;
	}

	public void setBookDecompLeaveTime(Date bookDecompLeaveTime) {
		this.bookDecompLeaveTime = bookDecompLeaveTime;
	}

	public Date getBookDecompArriveTime() {
		return this.bookDecompArriveTime;
	}

	public void setBookDecompArriveTime(Date bookDecompArriveTime) {
		this.bookDecompArriveTime = bookDecompArriveTime;
	}

	public String getBookDecompCarNumber() {
		return this.bookDecompCarNumber;
	}

	public void setBookDecompCarNumber(String bookDecompCarNumber) {
		this.bookDecompCarNumber = bookDecompCarNumber;
	}

}
