package hibernate;
// Generated 2017-4-26 14:48:25 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * Bookform generated by hbm2java
 */
public class Bookform implements java.io.Serializable {

	private String bookFormId;
	private Parkinglot parkinglot;
	private User user;
	private Integer bookFormFee;
	private Integer bookFormPayState;
	private Date bookFormBookDate;
	private Date bookFormStartTime;
	private Date bookFormEndTime;
	private Integer bookFormFine;
	private Integer bookFormFineType;
	private Date bookFormLeaveTime;
	private Date bookFormArriveTime;
	private String bookFormCarNumber;

	public Bookform() {
	}

	public Bookform(String bookFormId, Parkinglot parkinglot, User user) {
		this.bookFormId = bookFormId;
		this.parkinglot = parkinglot;
		this.user = user;
	}

	public Bookform(String bookFormId, Parkinglot parkinglot, User user, Integer bookFormFee, Integer bookFormPayState,
			Date bookFormBookDate, Date bookFormStartTime, Date bookFormEndTime, Integer bookFormFine,
			Integer bookFormFineType, Date bookFormLeaveTime, Date bookFormArriveTime, String bookFormCarNumber) {
		this.bookFormId = bookFormId;
		this.parkinglot = parkinglot;
		this.user = user;
		this.bookFormFee = bookFormFee;
		this.bookFormPayState = bookFormPayState;
		this.bookFormBookDate = bookFormBookDate;
		this.bookFormStartTime = bookFormStartTime;
		this.bookFormEndTime = bookFormEndTime;
		this.bookFormFine = bookFormFine;
		this.bookFormFineType = bookFormFineType;
		this.bookFormLeaveTime = bookFormLeaveTime;
		this.bookFormArriveTime = bookFormArriveTime;
		this.bookFormCarNumber = bookFormCarNumber;
	}

	public String getBookFormId() {
		return this.bookFormId;
	}

	public void setBookFormId(String bookFormId) {
		this.bookFormId = bookFormId;
	}

	public Parkinglot getParkinglot() {
		return this.parkinglot;
	}

	public void setParkinglot(Parkinglot parkinglot) {
		this.parkinglot = parkinglot;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Integer getBookFormFee() {
		return this.bookFormFee;
	}

	public void setBookFormFee(Integer bookFormFee) {
		this.bookFormFee = bookFormFee;
	}

	public Integer getBookFormPayState() {
		return this.bookFormPayState;
	}

	public void setBookFormPayState(Integer bookFormPayState) {
		this.bookFormPayState = bookFormPayState;
	}

	public Date getBookFormBookDate() {
		return this.bookFormBookDate;
	}

	public void setBookFormBookDate(Date bookFormBookDate) {
		this.bookFormBookDate = bookFormBookDate;
	}

	public Date getBookFormStartTime() {
		return this.bookFormStartTime;
	}

	public void setBookFormStartTime(Date bookFormStartTime) {
		this.bookFormStartTime = bookFormStartTime;
	}

	public Date getBookFormEndTime() {
		return this.bookFormEndTime;
	}

	public void setBookFormEndTime(Date bookFormEndTime) {
		this.bookFormEndTime = bookFormEndTime;
	}

	public Integer getBookFormFine() {
		return this.bookFormFine;
	}

	public void setBookFormFine(Integer bookFormFine) {
		this.bookFormFine = bookFormFine;
	}

	public Integer getBookFormFineType() {
		return this.bookFormFineType;
	}

	public void setBookFormFineType(Integer bookFormFineType) {
		this.bookFormFineType = bookFormFineType;
	}

	public Date getBookFormLeaveTime() {
		return this.bookFormLeaveTime;
	}

	public void setBookFormLeaveTime(Date bookFormLeaveTime) {
		this.bookFormLeaveTime = bookFormLeaveTime;
	}

	public Date getBookFormArriveTime() {
		return this.bookFormArriveTime;
	}

	public void setBookFormArriveTime(Date bookFormArriveTime) {
		this.bookFormArriveTime = bookFormArriveTime;
	}

	public String getBookFormCarNumber() {
		return this.bookFormCarNumber;
	}

	public void setBookFormCarNumber(String bookFormCarNumber) {
		this.bookFormCarNumber = bookFormCarNumber;
	}

}
