package hibernate;
// Generated 2017-5-7 13:38:56 by Hibernate Tools 3.5.0.Final

/**
 * Car generated by hbm2java
 */
public class Car implements java.io.Serializable {

	private Integer carId;
	private User user;
	private String carPlatenum;

	public Car() {
	}

	public Car(String carPlatenum) {
		this.carPlatenum = carPlatenum;
	}

	public Car(User user, String carPlatenum) {
		this.user = user;
		this.carPlatenum = carPlatenum;
	}

	public Integer getCarId() {
		return this.carId;
	}

	public void setCarId(Integer carId) {
		this.carId = carId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getCarPlatenum() {
		return this.carPlatenum;
	}

	public void setCarPlatenum(String carPlatenum) {
		this.carPlatenum = carPlatenum;
	}

}
