package hibernate;
// Generated 2017-5-7 13:38:56 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Device generated by hbm2java
 */
public class Device implements java.io.Serializable {

	private Integer deviceId;
	private String devicePlace;
	private String deviceName;
	private Date deviceMaintainDate;
	private Set maintainers = new HashSet(0);

	public Device() {
	}

	public Device(String devicePlace, String deviceName, Date deviceMaintainDate, Set maintainers) {
		this.devicePlace = devicePlace;
		this.deviceName = deviceName;
		this.deviceMaintainDate = deviceMaintainDate;
		this.maintainers = maintainers;
	}

	public Integer getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(Integer deviceId) {
		this.deviceId = deviceId;
	}

	public String getDevicePlace() {
		return this.devicePlace;
	}

	public void setDevicePlace(String devicePlace) {
		this.devicePlace = devicePlace;
	}

	public String getDeviceName() {
		return this.deviceName;
	}

	public void setDeviceName(String deviceName) {
		this.deviceName = deviceName;
	}

	public Date getDeviceMaintainDate() {
		return this.deviceMaintainDate;
	}

	public void setDeviceMaintainDate(Date deviceMaintainDate) {
		this.deviceMaintainDate = deviceMaintainDate;
	}

	public Set getMaintainers() {
		return this.maintainers;
	}

	public void setMaintainers(Set maintainers) {
		this.maintainers = maintainers;
	}

}
