package hibernate;
// Generated 2017-5-7 13:38:56 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * Exit generated by hbm2java
 */
public class Exit implements java.io.Serializable {

	private int exitParkingLotid;
	private Parkinglot parkinglot;
	private String exitCarNumber;
	private Integer exitFlag;
	private Date exitTime;

	public Exit() {
	}

	public Exit(Parkinglot parkinglot) {
		this.parkinglot = parkinglot;
	}

	public Exit(Parkinglot parkinglot, String exitCarNumber, Integer exitFlag, Date exitTime) {
		this.parkinglot = parkinglot;
		this.exitCarNumber = exitCarNumber;
		this.exitFlag = exitFlag;
		this.exitTime = exitTime;
	}

	public int getExitParkingLotid() {
		return this.exitParkingLotid;
	}

	public void setExitParkingLotid(int exitParkingLotid) {
		this.exitParkingLotid = exitParkingLotid;
	}

	public Parkinglot getParkinglot() {
		return this.parkinglot;
	}

	public void setParkinglot(Parkinglot parkinglot) {
		this.parkinglot = parkinglot;
	}

	public String getExitCarNumber() {
		return this.exitCarNumber;
	}

	public void setExitCarNumber(String exitCarNumber) {
		this.exitCarNumber = exitCarNumber;
	}

	public Integer getExitFlag() {
		return this.exitFlag;
	}

	public void setExitFlag(Integer exitFlag) {
		this.exitFlag = exitFlag;
	}

	public Date getExitTime() {
		return this.exitTime;
	}

	public void setExitTime(Date exitTime) {
		this.exitTime = exitTime;
	}

}
