package hibernate;
// Generated 2017-5-7 13:38:56 by Hibernate Tools 3.5.0.Final

/**
 * Nopay generated by hbm2java
 */
public class Nopay implements java.io.Serializable {

	private NopayId id;

	public Nopay() {
	}

	public Nopay(NopayId id) {
		this.id = id;
	}

	public NopayId getId() {
		return this.id;
	}

	public void setId(NopayId id) {
		this.id = id;
	}

}
