package hibernate;
// Generated 2017-4-26 14:48:25 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * Outlay generated by hbm2java
 */
public class Outlay implements java.io.Serializable {

	private Integer outlayId;
	private Cashier cashier;
	private Parkinglot parkinglot;
	private Integer outlayFormNum;
	private String outlayMatter;
	private Long outlayFee;
	private Date outlayDate;

	public Outlay() {
	}

	public Outlay(Parkinglot parkinglot) {
		this.parkinglot = parkinglot;
	}

	public Outlay(Cashier cashier, Parkinglot parkinglot, Integer outlayFormNum, String outlayMatter, Long outlayFee,
			Date outlayDate) {
		this.cashier = cashier;
		this.parkinglot = parkinglot;
		this.outlayFormNum = outlayFormNum;
		this.outlayMatter = outlayMatter;
		this.outlayFee = outlayFee;
		this.outlayDate = outlayDate;
	}

	public Integer getOutlayId() {
		return this.outlayId;
	}

	public void setOutlayId(Integer outlayId) {
		this.outlayId = outlayId;
	}

	public Cashier getCashier() {
		return this.cashier;
	}

	public void setCashier(Cashier cashier) {
		this.cashier = cashier;
	}

	public Parkinglot getParkinglot() {
		return this.parkinglot;
	}

	public void setParkinglot(Parkinglot parkinglot) {
		this.parkinglot = parkinglot;
	}

	public Integer getOutlayFormNum() {
		return this.outlayFormNum;
	}

	public void setOutlayFormNum(Integer outlayFormNum) {
		this.outlayFormNum = outlayFormNum;
	}

	public String getOutlayMatter() {
		return this.outlayMatter;
	}

	public void setOutlayMatter(String outlayMatter) {
		this.outlayMatter = outlayMatter;
	}

	public Long getOutlayFee() {
		return this.outlayFee;
	}

	public void setOutlayFee(Long outlayFee) {
		this.outlayFee = outlayFee;
	}

	public Date getOutlayDate() {
		return this.outlayDate;
	}

	public void setOutlayDate(Date outlayDate) {
		this.outlayDate = outlayDate;
	}

}
