package hibernate;
// Generated 2017-4-26 14:48:25 by Hibernate Tools 3.5.0.Final

/**
 * ParkinglotfloorId generated by hbm2java
 */
public class ParkinglotfloorId implements java.io.Serializable {

	private int parkingLotFloorId;
	private int parkingLotFloorLotid;

	public ParkinglotfloorId() {
	}

	public ParkinglotfloorId(int parkingLotFloorId, int parkingLotFloorLotid) {
		this.parkingLotFloorId = parkingLotFloorId;
		this.parkingLotFloorLotid = parkingLotFloorLotid;
	}

	public int getParkingLotFloorId() {
		return this.parkingLotFloorId;
	}

	public void setParkingLotFloorId(int parkingLotFloorId) {
		this.parkingLotFloorId = parkingLotFloorId;
	}

	public int getParkingLotFloorLotid() {
		return this.parkingLotFloorLotid;
	}

	public void setParkingLotFloorLotid(int parkingLotFloorLotid) {
		this.parkingLotFloorLotid = parkingLotFloorLotid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ParkinglotfloorId))
			return false;
		ParkinglotfloorId castOther = (ParkinglotfloorId) other;

		return (this.getParkingLotFloorId() == castOther.getParkingLotFloorId())
				&& (this.getParkingLotFloorLotid() == castOther.getParkingLotFloorLotid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getParkingLotFloorId();
		result = 37 * result + this.getParkingLotFloorLotid();
		return result;
	}

}
