package hibernate;
// Generated 2017-4-26 14:48:25 by Hibernate Tools 3.5.0.Final

/**
 * Parkingset generated by hbm2java
 */
public class Parkingset implements java.io.Serializable {

	private ParkingsetId id;
	private Parkinglotfloor parkinglotfloor;
	private Integer parkingSetLocationdx;
	private Integer parkingSetLocationdy;
	private Integer parkingSetStatus;
	private String parkingSetBookFormId;

	public Parkingset() {
	}

	public Parkingset(ParkingsetId id, Parkinglotfloor parkinglotfloor) {
		this.id = id;
		this.parkinglotfloor = parkinglotfloor;
	}

	public Parkingset(ParkingsetId id, Parkinglotfloor parkinglotfloor, Integer parkingSetLocationdx,
			Integer parkingSetLocationdy, Integer parkingSetStatus, String parkingSetBookFormId) {
		this.id = id;
		this.parkinglotfloor = parkinglotfloor;
		this.parkingSetLocationdx = parkingSetLocationdx;
		this.parkingSetLocationdy = parkingSetLocationdy;
		this.parkingSetStatus = parkingSetStatus;
		this.parkingSetBookFormId = parkingSetBookFormId;
	}

	public ParkingsetId getId() {
		return this.id;
	}

	public void setId(ParkingsetId id) {
		this.id = id;
	}

	public Parkinglotfloor getParkinglotfloor() {
		return this.parkinglotfloor;
	}

	public void setParkinglotfloor(Parkinglotfloor parkinglotfloor) {
		this.parkinglotfloor = parkinglotfloor;
	}

	public Integer getParkingSetLocationdx() {
		return this.parkingSetLocationdx;
	}

	public void setParkingSetLocationdx(Integer parkingSetLocationdx) {
		this.parkingSetLocationdx = parkingSetLocationdx;
	}

	public Integer getParkingSetLocationdy() {
		return this.parkingSetLocationdy;
	}

	public void setParkingSetLocationdy(Integer parkingSetLocationdy) {
		this.parkingSetLocationdy = parkingSetLocationdy;
	}

	public Integer getParkingSetStatus() {
		return this.parkingSetStatus;
	}

	public void setParkingSetStatus(Integer parkingSetStatus) {
		this.parkingSetStatus = parkingSetStatus;
	}

	public String getParkingSetBookFormId() {
		return this.parkingSetBookFormId;
	}

	public void setParkingSetBookFormId(String parkingSetBookFormId) {
		this.parkingSetBookFormId = parkingSetBookFormId;
	}

}
