package hibernate;
// Generated 2017-5-7 13:38:56 by Hibernate Tools 3.5.0.Final

/**
 * Parking generated by hbm2java
 */
public class Parking implements java.io.Serializable {

	private ParkingId id;

	public Parking() {
	}

	public Parking(ParkingId id) {
		this.id = id;
	}

	public ParkingId getId() {
		return this.id;
	}

	public void setId(ParkingId id) {
		this.id = id;
	}

}
