package hibernate;
// Generated 2017-5-7 13:38:56 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * ParkingId generated by hbm2java
 */
public class ParkingId implements java.io.Serializable {

	private String parkingBookid;
	private Integer parkingBehavior;
	private Integer parkingFine;
	private Date parkingArriveTime;
	private Date parkingLeaveTime;
	private Date parkingBookStart;
	private Date parkingBookEnd;
	private String parkingCarNumber;

	public ParkingId() {
	}

	public ParkingId(String parkingBookid) {
		this.parkingBookid = parkingBookid;
	}

	public ParkingId(String parkingBookid, Integer parkingBehavior, Integer parkingFine, Date parkingArriveTime,
			Date parkingLeaveTime, Date parkingBookStart, Date parkingBookEnd, String parkingCarNumber) {
		this.parkingBookid = parkingBookid;
		this.parkingBehavior = parkingBehavior;
		this.parkingFine = parkingFine;
		this.parkingArriveTime = parkingArriveTime;
		this.parkingLeaveTime = parkingLeaveTime;
		this.parkingBookStart = parkingBookStart;
		this.parkingBookEnd = parkingBookEnd;
		this.parkingCarNumber = parkingCarNumber;
	}

	public String getParkingBookid() {
		return this.parkingBookid;
	}

	public void setParkingBookid(String parkingBookid) {
		this.parkingBookid = parkingBookid;
	}

	public Integer getParkingBehavior() {
		return this.parkingBehavior;
	}

	public void setParkingBehavior(Integer parkingBehavior) {
		this.parkingBehavior = parkingBehavior;
	}

	public Integer getParkingFine() {
		return this.parkingFine;
	}

	public void setParkingFine(Integer parkingFine) {
		this.parkingFine = parkingFine;
	}

	public Date getParkingArriveTime() {
		return this.parkingArriveTime;
	}

	public void setParkingArriveTime(Date parkingArriveTime) {
		this.parkingArriveTime = parkingArriveTime;
	}

	public Date getParkingLeaveTime() {
		return this.parkingLeaveTime;
	}

	public void setParkingLeaveTime(Date parkingLeaveTime) {
		this.parkingLeaveTime = parkingLeaveTime;
	}

	public Date getParkingBookStart() {
		return this.parkingBookStart;
	}

	public void setParkingBookStart(Date parkingBookStart) {
		this.parkingBookStart = parkingBookStart;
	}

	public Date getParkingBookEnd() {
		return this.parkingBookEnd;
	}

	public void setParkingBookEnd(Date parkingBookEnd) {
		this.parkingBookEnd = parkingBookEnd;
	}

	public String getParkingCarNumber() {
		return this.parkingCarNumber;
	}

	public void setParkingCarNumber(String parkingCarNumber) {
		this.parkingCarNumber = parkingCarNumber;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ParkingId))
			return false;
		ParkingId castOther = (ParkingId) other;

		return ((this.getParkingBookid() == castOther.getParkingBookid())
				|| (this.getParkingBookid() != null && castOther.getParkingBookid() != null
						&& this.getParkingBookid().equals(castOther.getParkingBookid())))
				&& ((this.getParkingBehavior() == castOther.getParkingBehavior())
						|| (this.getParkingBehavior() != null && castOther.getParkingBehavior() != null
								&& this.getParkingBehavior().equals(castOther.getParkingBehavior())))
				&& ((this.getParkingFine() == castOther.getParkingFine())
						|| (this.getParkingFine() != null && castOther.getParkingFine() != null
								&& this.getParkingFine().equals(castOther.getParkingFine())))
				&& ((this.getParkingArriveTime() == castOther.getParkingArriveTime())
						|| (this.getParkingArriveTime() != null && castOther.getParkingArriveTime() != null
								&& this.getParkingArriveTime().equals(castOther.getParkingArriveTime())))
				&& ((this.getParkingLeaveTime() == castOther.getParkingLeaveTime())
						|| (this.getParkingLeaveTime() != null && castOther.getParkingLeaveTime() != null
								&& this.getParkingLeaveTime().equals(castOther.getParkingLeaveTime())))
				&& ((this.getParkingBookStart() == castOther.getParkingBookStart())
						|| (this.getParkingBookStart() != null && castOther.getParkingBookStart() != null
								&& this.getParkingBookStart().equals(castOther.getParkingBookStart())))
				&& ((this.getParkingBookEnd() == castOther.getParkingBookEnd())
						|| (this.getParkingBookEnd() != null && castOther.getParkingBookEnd() != null
								&& this.getParkingBookEnd().equals(castOther.getParkingBookEnd())))
				&& ((this.getParkingCarNumber() == castOther.getParkingCarNumber())
						|| (this.getParkingCarNumber() != null && castOther.getParkingCarNumber() != null
								&& this.getParkingCarNumber().equals(castOther.getParkingCarNumber())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getParkingBookid() == null ? 0 : this.getParkingBookid().hashCode());
		result = 37 * result + (getParkingBehavior() == null ? 0 : this.getParkingBehavior().hashCode());
		result = 37 * result + (getParkingFine() == null ? 0 : this.getParkingFine().hashCode());
		result = 37 * result + (getParkingArriveTime() == null ? 0 : this.getParkingArriveTime().hashCode());
		result = 37 * result + (getParkingLeaveTime() == null ? 0 : this.getParkingLeaveTime().hashCode());
		result = 37 * result + (getParkingBookStart() == null ? 0 : this.getParkingBookStart().hashCode());
		result = 37 * result + (getParkingBookEnd() == null ? 0 : this.getParkingBookEnd().hashCode());
		result = 37 * result + (getParkingCarNumber() == null ? 0 : this.getParkingCarNumber().hashCode());
		return result;
	}

}
