package hibernate;
// Generated 2017-5-7 13:38:56 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Rentform generated by hbm2java
 */
public class Rentform implements java.io.Serializable {

	private String rentFormId;
	private Parkinglot parkinglot;
	private User user;
	private Integer rentFormFee;
	private Date rentFormStartDate;
	private Date rentFormEndDate;
	private Date rentFormStartTime;
	private Date rentFormEndTime;
	private Date rentFormBookDate;
	private Integer rentFormPayStatus;
	private Set bookdecomps = new HashSet(0);

	public Rentform() {
	}

	public Rentform(String rentFormId, Parkinglot parkinglot, User user) {
		this.rentFormId = rentFormId;
		this.parkinglot = parkinglot;
		this.user = user;
	}

	public Rentform(String rentFormId, Parkinglot parkinglot, User user, Integer rentFormFee, Date rentFormStartDate,
			Date rentFormEndDate, Date rentFormStartTime, Date rentFormEndTime, Date rentFormBookDate,
			Integer rentFormPayStatus, Set bookdecomps) {
		this.rentFormId = rentFormId;
		this.parkinglot = parkinglot;
		this.user = user;
		this.rentFormFee = rentFormFee;
		this.rentFormStartDate = rentFormStartDate;
		this.rentFormEndDate = rentFormEndDate;
		this.rentFormStartTime = rentFormStartTime;
		this.rentFormEndTime = rentFormEndTime;
		this.rentFormBookDate = rentFormBookDate;
		this.rentFormPayStatus = rentFormPayStatus;
		this.bookdecomps = bookdecomps;
	}

	public String getRentFormId() {
		return this.rentFormId;
	}

	public void setRentFormId(String rentFormId) {
		this.rentFormId = rentFormId;
	}

	public Parkinglot getParkinglot() {
		return this.parkinglot;
	}

	public void setParkinglot(Parkinglot parkinglot) {
		this.parkinglot = parkinglot;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Integer getRentFormFee() {
		return this.rentFormFee;
	}

	public void setRentFormFee(Integer rentFormFee) {
		this.rentFormFee = rentFormFee;
	}

	public Date getRentFormStartDate() {
		return this.rentFormStartDate;
	}

	public void setRentFormStartDate(Date rentFormStartDate) {
		this.rentFormStartDate = rentFormStartDate;
	}

	public Date getRentFormEndDate() {
		return this.rentFormEndDate;
	}

	public void setRentFormEndDate(Date rentFormEndDate) {
		this.rentFormEndDate = rentFormEndDate;
	}

	public Date getRentFormStartTime() {
		return this.rentFormStartTime;
	}

	public void setRentFormStartTime(Date rentFormStartTime) {
		this.rentFormStartTime = rentFormStartTime;
	}

	public Date getRentFormEndTime() {
		return this.rentFormEndTime;
	}

	public void setRentFormEndTime(Date rentFormEndTime) {
		this.rentFormEndTime = rentFormEndTime;
	}

	public Date getRentFormBookDate() {
		return this.rentFormBookDate;
	}

	public void setRentFormBookDate(Date rentFormBookDate) {
		this.rentFormBookDate = rentFormBookDate;
	}

	public Integer getRentFormPayStatus() {
		return this.rentFormPayStatus;
	}

	public void setRentFormPayStatus(Integer rentFormPayStatus) {
		this.rentFormPayStatus = rentFormPayStatus;
	}

	public Set getBookdecomps() {
		return this.bookdecomps;
	}

	public void setBookdecomps(Set bookdecomps) {
		this.bookdecomps = bookdecomps;
	}

}
