package hibernate;
// Generated 2017-4-26 14:48:25 by Hibernate Tools 3.5.0.Final

/**
 * Strategy generated by hbm2java
 */
public class Strategy implements java.io.Serializable {

	private int strategyId;
	private Administrator administrator;
	private Parkinglot parkinglot;
	private Long strategyFee;
	private Long strategyLate;
	private Long strategyOverstay;
	private Long strategyMiss;
	private Long strategyOverrate;

	public Strategy() {
	}

	public Strategy(Parkinglot parkinglot) {
		this.parkinglot = parkinglot;
	}

	public Strategy(Administrator administrator, Parkinglot parkinglot, Long strategyFee, Long strategyLate,
			Long strategyOverstay, Long strategyMiss, Long strategyOverrate) {
		this.administrator = administrator;
		this.parkinglot = parkinglot;
		this.strategyFee = strategyFee;
		this.strategyLate = strategyLate;
		this.strategyOverstay = strategyOverstay;
		this.strategyMiss = strategyMiss;
		this.strategyOverrate = strategyOverrate;
	}

	public int getStrategyId() {
		return this.strategyId;
	}

	public void setStrategyId(int strategyId) {
		this.strategyId = strategyId;
	}

	public Administrator getAdministrator() {
		return this.administrator;
	}

	public void setAdministrator(Administrator administrator) {
		this.administrator = administrator;
	}

	public Parkinglot getParkinglot() {
		return this.parkinglot;
	}

	public void setParkinglot(Parkinglot parkinglot) {
		this.parkinglot = parkinglot;
	}

	public Long getStrategyFee() {
		return this.strategyFee;
	}

	public void setStrategyFee(Long strategyFee) {
		this.strategyFee = strategyFee;
	}

	public Long getStrategyLate() {
		return this.strategyLate;
	}

	public void setStrategyLate(Long strategyLate) {
		this.strategyLate = strategyLate;
	}

	public Long getStrategyOverstay() {
		return this.strategyOverstay;
	}

	public void setStrategyOverstay(Long strategyOverstay) {
		this.strategyOverstay = strategyOverstay;
	}

	public Long getStrategyMiss() {
		return this.strategyMiss;
	}

	public void setStrategyMiss(Long strategyMiss) {
		this.strategyMiss = strategyMiss;
	}

	public Long getStrategyOverrate() {
		return this.strategyOverrate;
	}

	public void setStrategyOverrate(Long strategyOverrate) {
		this.strategyOverrate = strategyOverrate;
	}

}
