package hibernate;
// Generated 2017-5-7 13:38:56 by Hibernate Tools 3.5.0.Final

/**
 * UsercreditnumId generated by hbm2java
 */
public class UsercreditnumId implements java.io.Serializable {

	private String userCreditNumCreditnum;
	private int userCreditNumUserid;

	public UsercreditnumId() {
	}

	public UsercreditnumId(String userCreditNumCreditnum, int userCreditNumUserid) {
		this.userCreditNumCreditnum = userCreditNumCreditnum;
		this.userCreditNumUserid = userCreditNumUserid;
	}

	public String getUserCreditNumCreditnum() {
		return this.userCreditNumCreditnum;
	}

	public void setUserCreditNumCreditnum(String userCreditNumCreditnum) {
		this.userCreditNumCreditnum = userCreditNumCreditnum;
	}

	public int getUserCreditNumUserid() {
		return this.userCreditNumUserid;
	}

	public void setUserCreditNumUserid(int userCreditNumUserid) {
		this.userCreditNumUserid = userCreditNumUserid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsercreditnumId))
			return false;
		UsercreditnumId castOther = (UsercreditnumId) other;

		return ((this.getUserCreditNumCreditnum() == castOther.getUserCreditNumCreditnum())
				|| (this.getUserCreditNumCreditnum() != null && castOther.getUserCreditNumCreditnum() != null
						&& this.getUserCreditNumCreditnum().equals(castOther.getUserCreditNumCreditnum())))
				&& (this.getUserCreditNumUserid() == castOther.getUserCreditNumUserid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUserCreditNumCreditnum() == null ? 0 : this.getUserCreditNumCreditnum().hashCode());
		result = 37 * result + this.getUserCreditNumUserid();
		return result;
	}

}
