package hibernate;
// Generated 2017-5-7 13:38:56 by Hibernate Tools 3.5.0.Final

/**
 * Usercreditnum generated by hbm2java
 */
public class Usercreditnum implements java.io.Serializable {

	private UsercreditnumId id;
	private User user;

	public Usercreditnum() {
	}

	public Usercreditnum(UsercreditnumId id, User user) {
		this.id = id;
		this.user = user;
	}

	public UsercreditnumId getId() {
		return this.id;
	}

	public void setId(UsercreditnumId id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
