package hibernate;
// Generated 2017-5-7 13:38:56 by Hibernate Tools 3.5.0.Final

/**
 * Worker generated by hbm2java
 */
public class Worker implements java.io.Serializable {

	private int workerId;
	private String workerGender;
	private String workerName;
	private String workerPhoneNum;
	private String workerJob;
	private String workerDepartment;
	private Administrator administrator;
	private Maintainer maintainer;
	private Cashier cashier;

	public Worker() {
	}

	public Worker(int workerId) {
		this.workerId = workerId;
	}

	public Worker(int workerId, String workerGender, String workerName, String workerPhoneNum, String workerJob,
			String workerDepartment, Administrator administrator, Maintainer maintainer, Cashier cashier) {
		this.workerId = workerId;
		this.workerGender = workerGender;
		this.workerName = workerName;
		this.workerPhoneNum = workerPhoneNum;
		this.workerJob = workerJob;
		this.workerDepartment = workerDepartment;
		this.administrator = administrator;
		this.maintainer = maintainer;
		this.cashier = cashier;
	}

	public int getWorkerId() {
		return this.workerId;
	}

	public void setWorkerId(int workerId) {
		this.workerId = workerId;
	}

	public String getWorkerGender() {
		return this.workerGender;
	}

	public void setWorkerGender(String workerGender) {
		this.workerGender = workerGender;
	}

	public String getWorkerName() {
		return this.workerName;
	}

	public void setWorkerName(String workerName) {
		this.workerName = workerName;
	}

	public String getWorkerPhoneNum() {
		return this.workerPhoneNum;
	}

	public void setWorkerPhoneNum(String workerPhoneNum) {
		this.workerPhoneNum = workerPhoneNum;
	}

	public String getWorkerJob() {
		return this.workerJob;
	}

	public void setWorkerJob(String workerJob) {
		this.workerJob = workerJob;
	}

	public String getWorkerDepartment() {
		return this.workerDepartment;
	}

	public void setWorkerDepartment(String workerDepartment) {
		this.workerDepartment = workerDepartment;
	}

	public Administrator getAdministrator() {
		return this.administrator;
	}

	public void setAdministrator(Administrator administrator) {
		this.administrator = administrator;
	}

	public Maintainer getMaintainer() {
		return this.maintainer;
	}

	public void setMaintainer(Maintainer maintainer) {
		this.maintainer = maintainer;
	}

	public Cashier getCashier() {
		return this.cashier;
	}

	public void setCashier(Cashier cashier) {
		this.cashier = cashier;
	}

}
